example:
	go test -v github.com/stratumn/zmey/example/...

race:
	go test -v -race github.com/stratumn/zmey/...

test:
	go test -v github.com/stratumn/zmey/...

lint:
	golint github.com/stratumn/zmey/...

.PHONY: example
