package forwarder

import (
	"github.com/stratumn/zmey"
)

// Forwarder implements Process interface and runs simple forwarding algorithm
type Forwarder struct {
	pid     int
	sendF   func(to int, payload interface{})
	returnF func(payload interface{})
	traceF  func(payload interface{})
	errorF  func(error)
}

// FCall represents a message exchanged between forwarder process and client
type FCall struct {
	// SequenceNumber is always-increasing message id
	SequenceNumber int
	// To is recepient id
	To int
	// Payload is just few randomly-generated bytes
	Payload []byte
}

// NewForwarder creates and returns the instance of Forwarder process
func NewForwarder(pid int) zmey.Process {
	return &Forwarder{pid: pid}
}

// Init initializes an instance of Forwarder process
func (f *Forwarder) Init(
	sendF func(to int, payload interface{}),
	returnF func(payload interface{}),
	traceF func(payload interface{}),
	errorF func(error),
) {
	f.sendF = sendF
	f.returnF = returnF
	f.traceF = traceF
	f.errorF = errorF
}

// ReceiveNet implements Process.ReceiveNet
func (f *Forwarder) ReceiveNet(from int, payload interface{}) {
	t := zmey.NewTracer("ReceiveNet")
	fcall, ok := payload.(FCall)
	if !ok {
		f.errorF(t.Errorf("cannot coerce to FCall: %+v", payload))
		return
	}

	if fcall.To != f.pid {
		f.errorF(t.Errorf("%d: incorrect recepient, should be %d", fcall.To, f.pid))
		return
	}

	f.traceF(t.Logf("%d return net", fcall.SequenceNumber))
	f.returnF(payload)
}

// ReceiveCall implements Process.ReceiveCall
func (f *Forwarder) ReceiveCall(c interface{}) {
	t := zmey.NewTracer("ReceiveCall")
	fcall, ok := c.(FCall)
	if !ok {
		f.errorF(t.Errorf("cannot coerce to FCall: %+v", c))
		return
	}

	t = t.Fork("FCall %d", fcall.SequenceNumber)

	f.traceF(t.Logf("receive"))

	if fcall.To == f.pid { // Local call
		f.traceF(t.Logf("return local"))
		f.returnF(c)
		return
	}

	f.traceF(t.Logf("forward"))
	f.sendF(fcall.To, fcall)
}

// Tick implements Process.Tick
func (f *Forwarder) Tick(uint) {}

// Start implements Process.Start
func (f *Forwarder) Start() {}
